### ISSUE TITLE
openFrameworks 0.8.0 compatible

### ISSUE THREAD

**Issue by dorald** [armadillu/ofxEasyRetina#3]
Hi armadillu .

EasyRetina doesn't work with new version oF 0.8.0 !

**Comment by armadillu** [comment]
hey yeah I am aware, no time to fix this right now sorry

**Comment by dorald** [comment]
ok thanks :)

**Comment by cerupcat** [comment]
I'm looking into this. I have it compiling, but it's drawing with the top in the center of the screen. I'm trying to figure out why that is.

**Comment by dorald** [comment]
hey @cerupcat 
any progress on this ?

**Comment by armadillu** [comment]
there's now a branch that adds 008 compatibility
